### ISSUE TITLE
TypeError: l is not iterable

### ISSUE THREAD

**Issue by Cicadadenis** [Bajdzis/vscode-awesome-tree#16]
```TypeError: l is not iterable
    at c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:24:127793
    at e.project (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:24:124620)
    at e._next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:11004)
    at e.next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1085)
    at e._next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:13260)
    at e.next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1085)
    at t.observe (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:13970)
    at e.dispatch [as work] (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:24:76949)
    at e._execute (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:20327)
    at e.execute (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:119947)
    at e.flush (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:18293)
    at e.schedule (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:119830)
    at e.t.schedule (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:120508)
    at e.schedule (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:18165)
    at e.scheduleMessage (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:24:77056)
    at e._next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:24:77151)
    at e.next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1085)
    at e._next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1414)
    at e.next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1085)
    at e.notifyNext (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:17294)
    at e._next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:4023)
    at e.next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1085)
    at e.notifyNext (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:17294)
    at e._next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:4023)
    at e.next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1085)
    at e.notifyNext (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:17294)
    at e._next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:4023)
    at e.next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1085)
    at c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:24:84092
    at a (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:4587)
    at e._innerSub (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:17076)
    at e._tryNext (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:16963)
    at e._next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:16786)
    at e.next (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:1085)
    at t.observe (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:13970)
    at e.dispatch [as work] (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\extension.js:16:38623)
    at e._execute (c:\Users\denis\.vscode\extensions\bajdzis.awesome-tree-1.7.0\out\exte

**Comment by Bajdzis** [comment]
@Cicadadenis  Thx for issue!  I have released new versions (2.0.0) changing the whole parse and compare files engine. 
The error will probably no longer occur.
