### ISSUE TITLE
xmax

### ISSUE THREAD

**Issue by MMAXKUBO** [Bajdzis/vscode-awesome-tree#22]
```Error: ENOENT: no such file or directory, open 'c:\Users\99893\.vscode\extensions\ms-vscode.cpptools-1.7.1\bin\vcruntime140.dll.tmp'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at e.project (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:37:12410)
    at e._tryNext (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:16:16889)
    at e._next (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:16:16791)
    at e.next (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:16:1085)
    at t.observe (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:16:13975)
    at e.dispatch [as work] (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:16:39955)
    at e._execute (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:16:20332)
    at e.execute (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:16:20148)
    at e.flush (c:\Users\99893\.vscode\extensions\bajdzis.awesome-tree-2.3.0\out\extension.js:16:18298)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by MMAXKUBO** [comment]
name davronbek
